url: "https://miidey1804.github.io"
baseurl: "/CloudForge_Inside"

title: "CloudForge Insider"
description: "Exclusive, in-depth insights into AWS, DevOps, and cloud strategies by CloudForge Solutions."

author:
  name: "adebambo Olumide"
  email: "info@cloudforge.com"
  phone: "08056138719"

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

