title: "CloudForge Insider"
description: "Exclusive insights into AWS, DevOps, and cloud strategies by CloudForge Solutions."
author: "CloudForge Solutions"
email: "info@cloudforge.com"
twitter_username: "cloudforgeHQ"
github_username: "miidey1804"

baseurl: "/CloudForge_Inside"
url: "https://miidey1804.github.io"

favicon: "/assets/images/favicon.ico"

# SEO & Social Preview
logo: "/assets/images/cloudforge-logo.png"
twitter_card: true
social:
  name: "CloudForge Solutions"
  links:
    - "https://twitter.com/cloudforgeHQ"
    - "https://github.com/miidey1804"

theme: minima

